sudo: required
language: python
dist: trusty

cache:
  apt: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/texlive'
    packages:
      - cmake
      - texlive-full

script:
  - mkdir build
  - cd build
  - cmake ..
  - make pdf