sudo: required
language: python
dist: trusty

cache:
  apt: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/texlive'
    packages:
      - cmake
      - texlive-full

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - mv ThesisRomainBrault.pdf ..
  - cd ..

after_success:
  # CREATE GIT TAG
  - git config --global user.email "ro.brault@gmail.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d")-$TRAVIS_BUILD_NUMBER
  - git add ThesisRomainBrault.pdf
  - git commit -m "Set build VERSION number"
  - git push both
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push --quiet git@github.com:RomainBrault/Thesis.git $GIT_TAG > /dev/null 2>&1

branches:
  except:
    - /^build-[0-9a-z\-]*/
