#!/usr/bin/env sh

set -e

cp bin/ThesisRomainBrault.pdf ~/Dropbox/CorrectionsRomain/Romain
cp bin/ThesisRomainBrault.pdf.asc ~/Dropbox/CorrectionsRomain/Romain

git pull github master
git add -A
git commit -m"Sync with Overleaf"
git push both


git pull github master
git add -A
git commit -m"Sync with Overleaf"
git push both
