#!/usr/bin/env sh

set -e

GPG_TTY=$(tty)
export GPG_TTY

cp bin/ThesisRomainBrault.pdf ~/Dropbox/CorrectionsRomain/Romain || true
cp bin/ThesisRomainBrault.pdf.asc ~/Dropbox/CorrectionsRomain/Romain || true

git pull origin master
git add -A
git commit -S -m"Sync"
git push origin master

